apiVersion: v1
kind: ServiceAccount
metadata:
  name: daltaners-service-account
  namespace: daltaners
  labels:
    app.kubernetes.io/part-of: daltaners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: daltaners-pod-reader
  namespace: daltaners
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: daltaners-pod-reader-binding
  namespace: daltaners
subjects:
  - kind: ServiceAccount
    name: daltaners-service-account
    namespace: daltaners
roleRef:
  kind: Role
  name: daltaners-pod-reader
  apiGroup: rbac.authorization.k8s.io
